using System.Collections.Generic;
using UnityEngine;

namespace MergeSurvivor.UI
{
    /// <summary>
    /// Lightweight runtime audio service. Loads clips on demand from
    /// <c>Resources/Audio/&lt;name&gt;</c> (generated by <c>Tools/generate_audio.py</c>),
    /// plays one-shot SFX through a pooled source, and crossfades a single looping
    /// music bed. Self-creates on first access so it works with the runtime
    /// bootstrap UI (no scene wiring required). Persists mute/volume in PlayerPrefs.
    /// </summary>
    public sealed class AudioManager : MonoBehaviour
    {
        // SFX names (filenames under Resources/Audio, without extension).
        public const string SfxPickup = "sfx_pickup";
        public const string SfxMerge = "sfx_merge";
        public const string SfxFightStart = "sfx_fight_start";
        public const string SfxWin = "sfx_win";
        public const string SfxLoss = "sfx_loss";
        public const string MusicGameplay = "music_gameplay";
        public const string MusicHub = "music_hub";

        private const string MutePrefKey = "merge_survivor_audio_muted";

        private static AudioManager _instance;
        private AudioSource _sfxSource;
        private AudioSource _musicSource;
        private readonly Dictionary<string, AudioClip> _cache = new();
        private string _currentMusic;
        private bool _muted;

        [Range(0f, 1f)] private float _sfxVolume = 0.9f;
        [Range(0f, 1f)] private float _musicVolume = 0.5f;

        public static AudioManager Instance => Ensure();

        public bool Muted => _muted;

        public static AudioManager Ensure()
        {
            if (_instance != null) return _instance;
            var go = new GameObject("AudioManager");
            _instance = go.AddComponent<AudioManager>();
            return _instance;
        }

        private void Awake()
        {
            if (_instance != null && _instance != this)
            {
                Destroy(gameObject);
                return;
            }
            _instance = this;
            DontDestroyOnLoad(gameObject);

            _sfxSource = gameObject.AddComponent<AudioSource>();
            _sfxSource.playOnAwake = false;
            _sfxSource.spatialBlend = 0f;

            _musicSource = gameObject.AddComponent<AudioSource>();
            _musicSource.playOnAwake = false;
            _musicSource.loop = true;
            _musicSource.spatialBlend = 0f;

            _muted = PlayerPrefs.GetInt(MutePrefKey, 0) != 0;
            ApplyMuteToSources();
        }

        private AudioClip Load(string clipName)
        {
            if (string.IsNullOrEmpty(clipName)) return null;
            if (_cache.TryGetValue(clipName, out var cached)) return cached;
            var clip = Resources.Load<AudioClip>("Audio/" + clipName);
            _cache[clipName] = clip; // cache misses too, to avoid repeated lookups
            return clip;
        }

        /// <summary>Play a one-shot SFX. <paramref name="overrideClip"/> wins if assigned.</summary>
        public void PlaySfx(string clipName, AudioClip overrideClip = null, float volumeScale = 1f)
        {
            if (_muted || _sfxSource == null) return;
            var clip = overrideClip != null ? overrideClip : Load(clipName);
            if (clip == null) return;
            _sfxSource.PlayOneShot(clip, Mathf.Clamp01(_sfxVolume * volumeScale));
        }

        /// <summary>Start a looping music bed. No-op if that track is already playing.</summary>
        public void PlayMusic(string clipName)
        {
            if (_musicSource == null) return;
            if (_currentMusic == clipName && _musicSource.isPlaying) return;
            var clip = Load(clipName);
            if (clip == null) return;
            _currentMusic = clipName;
            _musicSource.clip = clip;
            _musicSource.volume = _muted ? 0f : _musicVolume;
            _musicSource.Play();
        }

        public void StopMusic()
        {
            _currentMusic = null;
            if (_musicSource != null) _musicSource.Stop();
        }

        public void SetMuted(bool muted)
        {
            _muted = muted;
            PlayerPrefs.SetInt(MutePrefKey, muted ? 1 : 0);
            PlayerPrefs.Save();
            ApplyMuteToSources();
        }

        public bool ToggleMute()
        {
            SetMuted(!_muted);
            return _muted;
        }

        private void ApplyMuteToSources()
        {
            if (_musicSource != null) _musicSource.volume = _muted ? 0f : _musicVolume;
        }
    }
}
