#!/usr/bin/env python3
"""
Procedural audio generator for Merge Survivor: Board Quest.

Synthesizes all gameplay SFX and two music loops from scratch using only the
Python standard library (no numpy, no external samples). Output is 16-bit mono
PCM WAV written to Assets/_Project/Resources/Audio/.

License: CC0 / public domain. These files are 100% generated by this script;
there is no third-party sample content. Re-run to regenerate identically
(the synth is deterministic; any noise is seeded).

Usage:
    python Tools/generate_audio.py
"""

import math
import os
import random
import struct
import wave

SR = 44100  # sample rate
OUT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "Assets", "_Project", "Resources", "Audio",
)

# ---------------------------------------------------------------------------
# Low-level helpers (operate on python lists of float samples in [-1, 1])
# ---------------------------------------------------------------------------

NOTE_BASE = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def note_freq(name):
    """'A4' -> 440.0, 'C5' -> ~523.25. Sharps written as 'C#5'."""
    letter = name[0].upper()
    idx = 1
    semis = NOTE_BASE[letter]
    if len(name) > idx and name[idx] == "#":
        semis += 1
        idx += 1
    octave = int(name[idx:])
    midi = (octave + 1) * 12 + semis
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def adsr(n, a, d, s_level, r):
    """Build an n-sample ADSR amplitude envelope (times in samples)."""
    env = [0.0] * n
    for i in range(n):
        if i < a:
            env[i] = i / max(1, a)
        elif i < a + d:
            t = (i - a) / max(1, d)
            env[i] = 1.0 + (s_level - 1.0) * t
        elif i < n - r:
            env[i] = s_level
        else:
            t = (i - (n - r)) / max(1, r)
            env[i] = s_level * (1.0 - t)
    return env


def osc(freq, n, kind="sine", phase=0.0, harmonics=None):
    """Generate n samples of an oscillator. harmonics: list of (mult, amp)."""
    out = [0.0] * n
    w = 2.0 * math.pi * freq / SR
    if harmonics is None:
        if kind == "sine":
            harmonics = [(1, 1.0)]
        elif kind == "triangle":
            harmonics = [(1, 1.0), (3, -1 / 9.0), (5, 1 / 25.0), (7, -1 / 49.0)]
        elif kind == "saw":
            harmonics = [(k, ((-1) ** (k + 1)) / k) for k in range(1, 10)]
        elif kind == "square":
            harmonics = [(k, 1.0 / k) for k in (1, 3, 5, 7, 9)]
        elif kind == "bell":
            harmonics = [(1, 1.0), (2.01, 0.5), (2.99, 0.32), (4.2, 0.18), (5.4, 0.1)]
        else:
            harmonics = [(1, 1.0)]
    for mult, amp in harmonics:
        wm = w * mult
        for i in range(n):
            out[i] += amp * math.sin(wm * i + phase)
    return out


def tone(freq, dur, kind="sine", a=0.005, d=0.03, s=0.7, r=0.05, gain=0.5):
    n = int(dur * SR)
    sig = osc(freq, n, kind)
    env = adsr(n, int(a * SR), int(d * SR), s, int(r * SR))
    return [sig[i] * env[i] * gain for i in range(n)]


def noise(dur, gain=0.5, seed=0):
    rng = random.Random(seed)
    n = int(dur * SR)
    return [(rng.random() * 2 - 1) * gain for _ in range(n)]


def lowpass(sig, cutoff):
    """One-pole low-pass filter."""
    if not sig:
        return sig
    rc = 1.0 / (2 * math.pi * cutoff)
    dt = 1.0 / SR
    alpha = dt / (rc + dt)
    out = [0.0] * len(sig)
    out[0] = sig[0] * alpha
    for i in range(1, len(sig)):
        out[i] = out[i - 1] + alpha * (sig[i] - out[i - 1])
    return out


def mix(target, source, at=0):
    """Add source into target at sample offset `at`, growing target as needed."""
    end = at + len(source)
    if end > len(target):
        target.extend([0.0] * (end - len(target)))
    for i in range(len(source)):
        target[at + i] += source[i]
    return target


def reverb(sig, delays_ms=(37, 53, 71), decay=0.28):
    """Cheap multi-tap feedback-free reverb for a little space."""
    out = list(sig)
    for dm in delays_ms:
        d = int(dm * SR / 1000)
        for i in range(d, len(sig)):
            out[i] += sig[i - d] * decay
        decay *= 0.7
    return out


def normalize(sig, peak=0.89):
    m = max((abs(x) for x in sig), default=0.0)
    if m < 1e-6:
        return sig
    g = peak / m
    return [x * g for x in sig]


def soft_clip(sig):
    return [math.tanh(x) for x in sig]


def write_wav(path, sig, normalize_peak=0.89):
    sig = normalize(sig, normalize_peak)
    frames = bytearray()
    for x in sig:
        v = int(max(-1.0, min(1.0, x)) * 32767)
        frames += struct.pack("<h", v)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(bytes(frames))
    print(f"  wrote {os.path.relpath(path, OUT_DIR)}  ({len(sig)/SR:.2f}s)")


# ---------------------------------------------------------------------------
# SFX
# ---------------------------------------------------------------------------

def sfx_pickup():
    # Quick soft "tick/blip" with a tiny upward pitch chirp.
    n = int(0.09 * SR)
    out = [0.0] * n
    for i in range(n):
        t = i / n
        f = 520 + 340 * t
        out[i] = math.sin(2 * math.pi * f * i / SR)
    env = adsr(n, int(0.002 * SR), int(0.02 * SR), 0.4, int(0.05 * SR))
    out = [out[i] * env[i] for i in range(n)]
    return out


def sfx_merge():
    # Bright rising chime: 3-note major arpeggio with bell timbre + sparkle.
    out = []
    notes = ["C5", "E5", "G5"]
    step = int(0.075 * SR)
    for k, nm in enumerate(notes):
        t = tone(note_freq(nm), 0.45, kind="bell", a=0.002, d=0.12, s=0.25, r=0.3, gain=0.5)
        mix(out, t, k * step)
    # high sparkle tail
    mix(out, tone(note_freq("C6"), 0.5, kind="bell", a=0.002, d=0.2, s=0.15, r=0.3, gain=0.28),
        len(notes) * step)
    return reverb(out, decay=0.22)


def sfx_fight_start():
    # Drum thump + rising battle horn.
    out = []
    # kick: pitch-dropping sine + click
    n = int(0.22 * SR)
    kick = [0.0] * n
    for i in range(n):
        t = i / n
        f = 150 * (1 - t) + 45
        kick[i] = math.sin(2 * math.pi * f * i / SR) * (1 - t) ** 1.5
    mix(out, kick, 0)
    mix(out, lowpass(noise(0.04, 0.5, seed=1), 1800), 0)  # transient click
    # horn: detuned saws swelling up a fifth
    horn = []
    base = note_freq("G3")
    for det in (0.0, 4.0, -3.0):
        horn_v = tone(base + det, 0.55, kind="saw", a=0.06, d=0.1, s=0.8, r=0.18, gain=0.16)
        mix(horn, horn_v, 0)
    horn = lowpass(horn, 2400)
    mix(out, horn, int(0.06 * SR))
    return soft_clip(out)


def sfx_win():
    # Triumphant ascending fanfare: C E G C (major) bright + reverb tail.
    out = []
    seq = [("C5", 0.0), ("E5", 0.10), ("G5", 0.20), ("C6", 0.32)]
    for nm, t in seq:
        v = tone(note_freq(nm), 0.7, kind="bell", a=0.003, d=0.15, s=0.45, r=0.45, gain=0.42)
        # add octave shimmer
        v2 = tone(note_freq(nm) * 2, 0.6, kind="sine", a=0.003, d=0.2, s=0.2, r=0.35, gain=0.12)
        mix(v, v2, 0)
        mix(out, v, int(t * SR))
    # final sustained chord
    chord_at = int(0.32 * SR)
    for nm in ("C5", "E5", "G5", "C6"):
        mix(out, tone(note_freq(nm), 0.9, kind="triangle", a=0.01, d=0.25, s=0.4, r=0.5, gain=0.16),
            chord_at)
    return reverb(out, decay=0.3)


def sfx_loss():
    # Descending minor "wah-wahn" sting.
    out = []
    seq = [("E4", 0.0), ("D4", 0.16), ("C4", 0.32), ("A3", 0.5)]
    for nm, t in seq:
        v = tone(note_freq(nm), 0.6, kind="saw", a=0.01, d=0.1, s=0.6, r=0.3, gain=0.22)
        v = lowpass(v, 1500)
        mix(out, v, int(t * SR))
    # low pitch-bend "drop" at the end
    n = int(0.5 * SR)
    drop = [0.0] * n
    for i in range(n):
        t = i / n
        f = note_freq("A3") * (1 - 0.35 * t)
        drop[i] = math.sin(2 * math.pi * f * i / SR) * (1 - t)
    mix(out, [x * 0.3 for x in drop], int(0.5 * SR))
    return soft_clip(reverb(out, decay=0.2))


# ---------------------------------------------------------------------------
# Music loops
# ---------------------------------------------------------------------------

def build_loop(bpm, bars, chords, lead, kind_pad="triangle", kind_lead="sine",
               kick=True, lead_gain=0.16, pad_gain=0.09, seed=7):
    """Generic loop builder. chords: list of chord (list of note names) per bar.
    lead: list of (note, start_beat, dur_beats) over the whole loop (beat units)."""
    beat = 60.0 / bpm
    bar_len = int(beat * 4 * SR)
    total = bar_len * bars
    out = [0.0] * total

    # Pads: sustain each bar's chord softly.
    for b in range(bars):
        chord = chords[b % len(chords)]
        at = b * bar_len
        for nm in chord:
            pad = tone(note_freq(nm), beat * 4 * 1.02, kind=kind_pad,
                       a=0.08, d=0.3, s=0.7, r=0.4, gain=pad_gain)
            mix(out, pad, at)

    # Lead melody.
    for nm, sb, db in lead:
        at = int(sb * beat * SR)
        v = tone(note_freq(nm), db * beat * 0.95, kind=kind_lead,
                 a=0.01, d=0.08, s=0.6, r=0.12, gain=lead_gain)
        v = reverb(v, delays_ms=(53, 79), decay=0.18)
        mix(out, v, at)

    # Simple kick on beats 1 and 3 of every bar.
    if kick:
        n = int(0.18 * SR)
        for b in range(bars):
            for beat_i in (0, 2):
                at = b * bar_len + int(beat_i * beat * SR)
                k = [0.0] * n
                for i in range(n):
                    t = i / n
                    f = 130 * (1 - t) + 45
                    k[i] = math.sin(2 * math.pi * f * i / SR) * (1 - t) ** 1.4 * 0.5
                mix(out, k, at)

    return soft_clip(out)


def music_gameplay():
    # Upbeat, warm desert-adventure loop in A minor / C major feel, 8 bars.
    bpm = 104
    chords = [
        ["A3", "C4", "E4"],   # Am
        ["F3", "A3", "C4"],   # F
        ["C4", "E4", "G4"],   # C
        ["G3", "B3", "D4"],   # G
        ["A3", "C4", "E4"],   # Am
        ["F3", "A3", "C4"],   # F
        ["C4", "E4", "G4"],   # C
        ["E3", "G#3", "B3"],  # E (lift back to Am)
    ]
    # A pentatonic-ish bouncy lead (beats are 0-indexed across the 8 bars).
    scale = ["A4", "C5", "D5", "E5", "G5"]
    rng = random.Random(11)
    lead = []
    beat = 0.0
    bars = 8
    while beat < bars * 4 - 0.5:
        nm = scale[rng.randrange(len(scale))]
        dur = rng.choice([0.5, 0.5, 1.0])
        lead.append((nm, beat, dur))
        beat += dur
    return build_loop(bpm, bars, chords, lead, kind_pad="triangle",
                      kind_lead="sine", kick=True, lead_gain=0.15, pad_gain=0.08)


def music_hub():
    # Calm, slow merchant-tent loop, sparse arpeggio over warm pads, 8 bars.
    bpm = 72
    chords = [
        ["C4", "E4", "G4"],   # C
        ["A3", "C4", "E4"],   # Am
        ["F3", "A3", "C4"],   # F
        ["G3", "B3", "D4"],   # G
        ["C4", "E4", "G4"],
        ["A3", "C4", "E4"],
        ["D4", "F4", "A4"],   # Dm
        ["G3", "B3", "D4"],   # G
    ]
    # Gentle descending/ascending arpeggio, mostly quarter & half notes.
    pattern = ["E5", "G5", "C6", "G5", "A5", "E5", "D5", "G5"]
    lead = []
    bars = 8
    for b in range(bars):
        for j in range(2):  # two notes per bar, very sparse
            nm = pattern[(b * 2 + j) % len(pattern)]
            lead.append((nm, b * 4 + j * 2, 1.5))
    return build_loop(bpm, bars, chords, lead, kind_pad="triangle",
                      kind_lead="bell", kick=False, lead_gain=0.12, pad_gain=0.10)


# ---------------------------------------------------------------------------

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Generating audio into {OUT_DIR}")
    sfx = {
        "sfx_pickup": sfx_pickup(),
        "sfx_merge": sfx_merge(),
        "sfx_fight_start": sfx_fight_start(),
        "sfx_win": sfx_win(),
        "sfx_loss": sfx_loss(),
    }
    for name, sig in sfx.items():
        write_wav(os.path.join(OUT_DIR, name + ".wav"), sig, normalize_peak=0.9)

    print("Generating music loops (this takes a few seconds)...")
    write_wav(os.path.join(OUT_DIR, "music_gameplay.wav"), music_gameplay(), normalize_peak=0.7)
    write_wav(os.path.join(OUT_DIR, "music_hub.wav"), music_hub(), normalize_peak=0.62)
    print("Done.")


if __name__ == "__main__":
    main()
