#!/usr/bin/env python3
"""
Procedural gem-sprite generator for the upper merge tiers (T5, T6).

Renders classic faceted "gem" silhouettes with a vertical gradient, a couple of
cut facets, a specular highlight and a dark outline, on a transparent background.
Rendered at 4x and box-downsampled for clean anti-aliased edges. Pure standard
library (zlib for PNG compression) -- no PIL/numpy, no third-party art.

License: CC0 / public domain (100% generated by this script).

Usage:
    python Tools/generate_items.py
"""

import math
import os
import struct
import zlib

OUT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "Assets", "_Project", "Art", "Items",
)

SIZE = 256
SS = 4              # supersample factor
W = SIZE * SS


def lerp(a, b, t):
    return a + (b - a) * t


def mix(c1, c2, t):
    return tuple(int(round(lerp(c1[i], c2[i], t))) for i in range(3))


def point_in_poly(px, py, poly):
    inside = False
    n = len(poly)
    j = n - 1
    for i in range(n):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if ((yi > py) != (yj > py)) and (px < (xj - xi) * (py - yi) / (yj - yi + 1e-9) + xi):
            inside = not inside
        j = i
    return inside


def gem_polygon(cx, cy, rx, ry):
    """Hexagonal brilliant-cut silhouette: flat top table, wide girdle, point."""
    top = cy - ry
    girdle = cy - ry * 0.18
    bottom = cy + ry
    return [
        (cx - rx * 0.45, top),            # table left
        (cx + rx * 0.45, top),            # table right
        (cx + rx, girdle),                # girdle right
        (cx + rx * 0.30, bottom),         # pavilion right
        (cx - rx * 0.30, bottom),         # pavilion left
        (cx - rx, girdle),                # girdle left
    ]


def render_gem(top_color, bottom_color, facet_color, highlight=(255, 255, 255)):
    """Return SIZE x SIZE RGBA bytes."""
    cx = cy = W / 2
    rx = W * 0.34
    ry = W * 0.40
    poly = gem_polygon(cx, cy, rx, ry)
    table_y = cy - ry
    girdle_y = cy - ry * 0.18
    bottom_y = cy + ry

    outline = (max(0, top_color[0] // 4), max(0, top_color[1] // 4), max(0, top_color[2] // 4))
    seam = (max(0, facet_color[0] - 30), max(0, facet_color[1] - 30), max(0, facet_color[2] - 30))

    # Render supersampled RGBA.
    buf = bytearray(W * W * 4)
    for y in range(W):
        for x in range(W):
            idx = (y * W + x) * 4
            inside = point_in_poly(x + 0.5, y + 0.5, poly)
            if not inside:
                # Outline: inside a slightly inflated polygon but outside the gem.
                infl = [(cx + (vx - cx) * 1.05, cy + (vy - cy) * 1.05) for (vx, vy) in poly]
                if point_in_poly(x + 0.5, y + 0.5, infl):
                    buf[idx:idx + 4] = bytes((*outline, 255))
                continue

            # Vertical gradient body.
            t = (y - table_y) / max(1.0, (bottom_y - table_y))
            t = min(1.0, max(0.0, t))
            col = mix(top_color, bottom_color, t)

            # Pavilion facets below the girdle: a left/right "V" split for a cut look.
            if y > girdle_y:
                ft = (y - girdle_y) / max(1.0, (bottom_y - girdle_y))
                base = mix(facet_color, bottom_color, ft)
                # central V seam
                rel = (x - cx) / rx
                shade = 0.78 + 0.22 * abs(rel)
                col = tuple(min(255, int(base[i] * shade)) for i in range(3))
                if abs(x - cx) < SS * 1.5:
                    col = seam
            else:
                # Crown table: lighter trapezoid near the top.
                if y < girdle_y - (girdle_y - table_y) * 0.35:
                    col = mix(col, highlight, 0.18)

            # Specular highlight blob, upper-left of the table.
            hx, hy = cx - rx * 0.30, table_y + ry * 0.22
            d = math.hypot(x - hx, y - hy) / (rx * 0.5)
            if d < 1.0:
                col = mix(col, highlight, (1.0 - d) * 0.6)

            buf[idx:idx + 4] = bytes((col[0], col[1], col[2], 255))

    return downsample(buf)


def downsample(buf):
    """Box-downsample W x W RGBA -> SIZE x SIZE RGBA (premultiplied-correct alpha)."""
    out = bytearray(SIZE * SIZE * 4)
    for oy in range(SIZE):
        for ox in range(SIZE):
            r = g = b = a = 0
            for dy in range(SS):
                for dx in range(SS):
                    sx = ox * SS + dx
                    sy = oy * SS + dy
                    si = (sy * W + sx) * 4
                    sa = buf[si + 3]
                    r += buf[si] * sa
                    g += buf[si + 1] * sa
                    b += buf[si + 2] * sa
                    a += sa
            n = SS * SS
            oa = a // n
            if a > 0:
                r, g, b = r // a, g // a, b // a
            else:
                r = g = b = 0
            oi = (oy * SIZE + ox) * 4
            out[oi:oi + 4] = bytes((r, g, b, oa))
    return out


def write_png(path, rgba):
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    raw = bytearray()
    for y in range(SIZE):
        raw.append(0)  # filter type 0
        raw += rgba[y * SIZE * 4:(y + 1) * SIZE * 4]
    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(png)
    print(f"  wrote {os.path.relpath(path, OUT_DIR)}")


# (top, bottom, facet, highlight) per tier. Hues track DesertTheme.TierColor so the
# board pieces read consistently whether drawn from sprite or color fallback.
TIERS = {
    1: ((175, 225, 140), (70, 130, 45), (120, 185, 90), (240, 255, 235)),    # green emerald
    2: ((150, 200, 255), (30, 80, 175), (90, 150, 230), (235, 245, 255)),    # blue lapis
    3: ((205, 150, 240), (95, 45, 150), (165, 95, 210), (245, 235, 255)),    # purple amethyst
    4: ((255, 225, 120), (170, 120, 20), (235, 190, 55), (255, 250, 225)),   # gold topaz
    5: ((255, 140, 150), (150, 18, 40), (210, 40, 70), (255, 235, 235)),     # ruby (T5)
    6: ((245, 250, 255), (120, 175, 225), (185, 220, 250), (255, 255, 255)), # diamond (T6)
}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Generating item sprites into {OUT_DIR}")
    for tier, (top, bottom, facet, hi) in TIERS.items():
        img = render_gem(top_color=top, bottom_color=bottom, facet_color=facet, highlight=hi)
        write_png(os.path.join(OUT_DIR, f"item_crystal_t{tier}.png"), img)
    print("Done.")


if __name__ == "__main__":
    main()
